// FateConnect/Web/src/components/Footer/index.tsx
import EmailIcon from '@mui/icons-material/Email';
import LocationOnIcon from '@mui/icons-material/LocationOn';
import PhoneIcon from '@mui/icons-material/Phone';
import Typography from '@mui/material/Typography';

import { APP_CONTACT } from '@app/constants/appContact';
import { LandingSection } from '@app/routes/paths';
import {
  ContactItem,
  ContactsContainer,
  CopyrightContainer,
  FooterDivider,
  FooterRoot,
} from './styles';

export function Footer() {
  return (
    <FooterRoot>
      <ContactsContainer id={LandingSection.CONTACT}>
        <Typography variant="h2">Entre em contato</Typography>

        <ContactItem>
          <EmailIcon fontSize="small" />
          <Typography variant="caption">{APP_CONTACT.email}</Typography>
        </ContactItem>
        <ContactItem>
          <PhoneIcon fontSize="small" />
          <Typography variant="caption">{APP_CONTACT.phone}</Typography>
        </ContactItem>
        <ContactItem>
          <LocationOnIcon fontSize="small" />
          <Typography variant="caption">{APP_CONTACT.address}</Typography>
        </ContactItem>
      </ContactsContainer>

      <FooterDivider />

      <CopyrightContainer>
        <Typography variant="caption">© 2026 FateConnect. Todos os direitos reservados.</Typography>
        <Typography variant="caption">Desenvolvido para facilitar a vida do Fatecano.</Typography>
      </CopyrightContainer>
    </FooterRoot>
  );
}

// FateConnect/Front/src/app/shared/ui/footer/footer.component.ts
import { Component } from '@angular/core';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { faEnvelope, faLocationDot, faPhone } from '@fortawesome/free-solid-svg-icons';
import { APP_CONTACT } from '../../constants/app-contact';
import { TypographyComponent } from '../typography/typography';

@Component({
  selector: 'app-footer',
  imports: [FontAwesomeModule, TypographyComponent],
  templateUrl: './footer.component.html',
  styleUrl: './footer.component.scss',
})
export class FooterComponent {
  readonly contact = APP_CONTACT;
  readonly envelopeIcon = faEnvelope;
  readonly phoneIcon = faPhone;
  readonly locationIcon = faLocationDot;
}

<div class="footer">
  <div id="contato" class="contacts-container">
    <app-typography variant="h2">Entre em contato</app-typography>
    <div class="contact-item">
      <fa-icon [icon]="envelopeIcon" size="sm"></fa-icon>
      <app-typography variant="caption">{{ contact.email }}</app-typography>
    </div>
    <div class="contact-item">
      <fa-icon [icon]="phoneIcon" size="sm"></fa-icon>
      <app-typography variant="caption">{{ contact.phone }}</app-typography>
    </div>
    <div class="contact-item">
      <fa-icon [icon]="locationIcon" size="sm"></fa-icon>
      <app-typography variant="caption">{{ contact.address }}</app-typography>
    </div>
  </div>

  <div class="divider-container"></div>

  <div class="copyright-container">
    <app-typography variant="caption">© 2026 FateConnect. Todos os direitos reservados.</app-typography>
    <app-typography variant="caption">Desenvolvido para facilitar a vida do Fatecano.</app-typography>
  </div>
</div>
